categories: Categories
tags: Tags
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
home_title: '好处@haochu.me'

Home: Home
Archives: Archives
Categories: Categories
Tags: Tags
About: About
Links: Links
RSS: RSS
